table Dates
	lineageTag: 546fe641-49e2-42ad-8993-9b4091e48b37

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 13f0fe59-57f2-43a4-b37a-a60145a4c918
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 96168432-2ea4-4a43-a431-e0c29fad516c
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 304326bc-2f4b-42ae-83c8-817b18063fdd
		summarizeBy: none
		sourceColumn: Month Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: fcc3a1ed-0d23-43f0-b9ef-e474453f8e71
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Name Short'
		dataType: string
		lineageTag: 1b90f683-3b14-46e4-bbbd-628641ba3305
		summarizeBy: none
		sourceColumn: Month Name Short
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Day of Month'
		dataType: int64
		formatString: 0
		lineageTag: f3368a23-f945-4c15-ac92-e5ba88846ed3
		summarizeBy: none
		sourceColumn: Day of Month

		annotation SummarizationSetBy = Automatic

	column day_of_week_number
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 33c0c57a-1b7b-480a-ad1c-5863d21b3c64
		summarizeBy: none
		sourceColumn: day_of_week_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: a8444631-198e-413d-83d7-5c69cee73f96
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: day_of_week_number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Day Name Short'
		dataType: string
		lineageTag: ed0697e6-cc2c-40c7-a9c1-61d33b967983
		summarizeBy: none
		sourceColumn: Day Name Short
		sortByColumn: day_of_week_number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Week Number'
		dataType: int64
		formatString: 0
		lineageTag: 5f08a7bc-b50d-4027-ab3a-e00280f3a97a
		summarizeBy: none
		sourceColumn: Week Number

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 8047c167-8180-4923-9e57-9faba052ebf1
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: b0eb3494-f280-4871-b1bb-0a7018c4b0f3
		summarizeBy: none
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: string
		lineageTag: b2a451df-5275-43ed-b7c0-a3b68f629c0a
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column 'Is Weekend'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 333221e4-2561-4422-94f6-0c4386933ab2
		summarizeBy: none
		sourceColumn: Is Weekend

		annotation SummarizationSetBy = Automatic

	column Year-Month
		dataType: string
		lineageTag: e8da812a-2182-4ccd-a652-519db73f0b98
		summarizeBy: none
		sourceColumn: Year-Month

		annotation SummarizationSetBy = Automatic

	column 'Year-Month int'
		dataType: int64
		formatString: 0
		lineageTag: bb976cb7-8034-448e-b95c-b60659a2dc91
		summarizeBy: none
		sourceColumn: Year-Month int

		annotation SummarizationSetBy = Automatic

	column 'Date key'
		dataType: int64
		formatString: 0
		lineageTag: 9b5504ba-18db-47e1-8f04-2dfe18d25b36
		summarizeBy: none
		sourceColumn: Date key

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: fa338ba8-9b11-4bae-bb67-c4e42e6dbdf4
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: int64
		formatString: 0
		lineageTag: 5988a33a-e29a-482f-ad47-70d62b481b12
		summarizeBy: none
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: e47c356f-482a-4762-8d2f-f38d749ae1de

		level Year
			lineageTag: 8232c163-b22d-4276-b50e-3e33a808cff7
			column: Year

		level Month
			lineageTag: b387d2a0-47ef-4c33-bd14-da07f66fbf39
			column: Month

		level 'Day Name Short'
			lineageTag: d8e60625-0a61-4616-8aff-fce3a956b9af
			column: 'Day Name Short'

		level 'Day of Month'
			lineageTag: 8ecf49d9-316a-4b16-9775-35cddc6f9f6a
			column: 'Day of Month'

	partition Dates = m
		mode: import
		source = ```
				let
				    Source = Sql.Database("n4hpkudlw7tetjb7goluxudy5m-2ze2rsdhnsjuhenmvjdyqi4mpi.datawarehouse.fabric.microsoft.com", "References"),
				    MaxDate = Date.From(List.Max(#"Solar Telemetry"[ReadingDateLocal])),
				    MinDate = Date.From(List.Min(#"Solar Telemetry"[ReadingDateLocal])),
				    dbo_calendar = Source{[Schema="dbo",Item="calendar"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_calendar, each Date.From([date]) >= MinDate and Date.From([date]) <= Date.AddDays(MaxDate,1)),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"month_name", "Month"}, {"month_number", "Month Number"}, {"month_name_short", "Month Name Short"}, {"season", "Season"}, {"quarter", "Quarter"}, {"year", "Year"}, {"week_of_year", "Week Number"}, {"year_month", "Year-Month"}, {"year_month_int", "Year-Month int"}, {"date", "Date"}, {"date_key", "Date key"}, {"day_of_month", "Day of Month"}, {"day_of_week_name", "Day Name"}, {"day_of_week_name_short", "Day Name Short"}, {"day_of_year", "Day of Year"}, {"is_weekend", "Is Weekend"}, {"fiscal_year", "Fiscal Year"}}),
				    #"Sorted Rows" = Table.Sort(#"Renamed Columns",{{"Date", Order.Descending}})
				    
				in
				    #"Sorted Rows"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

